Scapture-Hackaton/Scapture-Server

.idea/vcs.xml
scapture/src/main/java/com/server/scapture/domain/User.java
scapture/src/main/java/com/server/scapture/util/S3/S3Service.java
scapture/src/main/resources/application.properties

- close #2 
DB 생성 및 연동 & S3 연동

✨ Add DB & S3 Info

---

scapture/src/main/java/com/server/scapture/domain/Comment.java
scapture/src/main/java/com/server/scapture/domain/Field.java
scapture/src/main/java/com/server/scapture/domain/Schedule.java
scapture/src/main/java/com/server/scapture/video/controller/VideoController.java

- close #6 
Entity 생성 - Field, Schedule, Comment

Entity 생성 - Field, Schedule, Comment

---

scapture/src/main/java/com/server/scapture/domain/Event.java
scapture/src/main/java/com/server/scapture/domain/Image.java
scapture/src/main/java/com/server/scapture/domain/Subscribe.java
scapture/src/main/java/com/server/scapture/domain/User.java
scapture/src/main/java/com/server/scapture/domain/Video.java

- close #7 
Entity 생성 - Image, Subscribe. Event

⚙️ [Setting] Entity 생성 - Image, Subscribe. Event

---

scapture/src/main/java/com/server/scapture/domain/CommentLike.java
scapture/src/main/java/com/server/scapture/domain/Download.java
scapture/src/main/java/com/server/scapture/domain/Reservation.java
scapture/src/main/java/com/server/scapture/domain/Store.java
scapture/src/main/java/com/server/scapture/domain/VideoLike.java

- close #8 
Entity 생성 - Reservation, VideoLike, CommentLike, Store, Download

⚙️ [Setting] Entity 생성 - Reservation, VideoLike, CommentLike, Store, Download

---

scapture/src/main/java/com/server/scapture/video/controller/VideoController.java

⚙️ [Setting] Package & Directory 작업 구조 설정 

---

scapture/build.gradle

- close #21 
의존성 추가 및 application-secret.properties 내용 추가
카톡으로 application-secret.properties 수정사항 보내드리겠습니다

⬆️ 소셜로그인 API 구현 - 의존성 추가

---

scapture/build.gradle
scapture/src/main/java/com/server/scapture/user/JwtUtil.java
scapture/src/main/java/com/server/scapture/user/handler/OAuthLoginSuccessHandler.java
scapture/src/main/java/com/server/scapture/user/repository/UserRepository.java

- close #27 
조금 뒤에  채워넣겠습니다..!

[User] 소셜로그인 API 구현 - 수정

---

scapture/src/main/java/com/server/scapture/stadium/controller/StadiumController.java
scapture/src/main/java/com/server/scapture/stadium/dto/GetStadiumResponseDto.java
scapture/src/main/java/com/server/scapture/stadium/repository/StadiumRepository.java
scapture/src/main/java/com/server/scapture/stadium/service/StadiumService.java
scapture/src/main/java/com/server/scapture/stadium/service/StadiumServiceImpl.java

- close #34 
경기장 검색 API 구현
keyword 검색 구현

✨[Feat] 경기장 검색 API 구현

---

scapture/src/main/java/com/server/scapture/stadium/service/StadiumServiceImpl.java

- close #40 
200(No Content) 예외 추가
리턴 메세지 수정

🚨 [Fix] 구장 경기장 조회 API 수정

---

scapture/src/main/java/com/server/scapture/ScaptureApplication.java
scapture/src/main/java/com/server/scapture/domain/Schedule.java
scapture/src/main/java/com/server/scapture/domain/Stadium.java
scapture/src/main/java/com/server/scapture/field/dto/FieldAttributeResponseDto.java
scapture/src/main/java/com/server/scapture/field/dto/SimpleFieldResponseDto.java
scapture/src/main/java/com/server/scapture/field/repository/FieldRepository.java
scapture/src/main/java/com/server/scapture/field/service/FieldServiceImpl.java
scapture/src/main/java/com/server/scapture/image/dto/SimpleImageResponseDto.java
scapture/src/main/java/com/server/scapture/image/repository/ImageRepository.java
scapture/src/main/java/com/server/scapture/stadium/controller/StadiumController.java
scapture/src/main/java/com/server/scapture/stadium/dto/CreateStadiumRequestDto.java
scapture/src/main/java/com/server/scapture/stadium/dto/GetStadiumDetailDto.java
scapture/src/main/java/com/server/scapture/stadium/dto/GetStadiumResponseDto.java
scapture/src/main/java/com/server/scapture/stadium/service/StadiumService.java
scapture/src/main/java/com/server/scapture/stadium/service/StadiumServiceImpl.java
scapture/src/main/resources/application.properties

- close #36 
Image List 포함
Field List 포함
명세서 내 예외 처리

✨ [Feat] 경기장 세부 조회 API 구현

---

scapture/src/main/java/com/server/scapture/domain/Schedule.java
scapture/src/main/java/com/server/scapture/domain/Subscribe.java
scapture/src/main/java/com/server/scapture/schedule/dto/CreateScheduleRequestDto.java
scapture/src/main/java/com/server/scapture/schedule/service/ScheduleServiceImpl.java
scapture/src/main/java/com/server/scapture/subscribe/dto/CreateSubscribeRequestDto.java

- close #48 
Schedule : HH:mm ~ HH:mm (start ~ end) 형식 변환 Logic 구현
Schedule : yyyy.MM.dd.E 형식 변환 Logic 구현
Schedule: MM.dd.E 형식 변환 Logic 구현
Subscribe: yyyy.MM.dd 형식 변환 Logic 구현
Subscribe createSubscribeRequestDto : String -> LocalDateTime Logic 구현
@khyaejin 
시작 시간 & 종료 시간 따로 주는게 좋을까요??
지금은 "10:00 ~ 12:00" 이런 식으로 합쳐서 줍니다.

⚙️ [Setting] LocalDateTime 관련 Logic 구현

---

scapture/src/main/java/com/server/scapture/util/config/SecurityConfig.java

카카오 소셜로그인 관련 공부 및 정리
노션 링크 : https://hyejinworkspace.notion.site/google-naver-kakao-50a6132af59a4c6785cbce0637c4ff90?pvs=4
- close #45 
(카카오) 소셜로그인 관련 공부 및 정리

📝 [Docs] 카카오 소셜로그인 - 공부 및 정리

---

scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
scapture/src/main/java/com/server/scapture/video/dto/VideoCreateDetailDto.java
scapture/src/main/java/com/server/scapture/video/dto/VideoCreateRequestDto.java
scapture/src/main/java/com/server/scapture/video/service/VideoService.java
scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java

✨ [Feat] 영상 업로드 API 구현

---

scapture/src/main/java/com/server/scapture/schedule/service/ScheduleServiceImpl.java

- close #63 
운영 일정 생성 API 수정 - 예약 여부 Default 값 주입

🚨 [Fix] 운영 일정 생성 API 수정 - 예약 여부 Default 값 주입

---

scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
scapture/src/main/java/com/server/scapture/video/dto/GetVideosByLikeCountResponseDto.java
scapture/src/main/java/com/server/scapture/video/repository/VideoRepository.java
scapture/src/main/java/com/server/scapture/video/service/VideoService.java
scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java

- close #72 
인기 영상 조회 API 구현
좋아요 순 상위 10개 동영상 리스트 리턴
date **MM.dd.E** Format

✨ [Feat] 인기 영상 조회 API 구현

---

scapture/src/main/java/com/server/scapture/oauth/controller/SignController.java
scapture/src/main/java/com/server/scapture/oauth/jwt/JwtUtil.java

- close #67 
ex) Issue 내용 간단히 기재
후에 수정
https://www.notion.so/api-oauth-social-test-find-user-140508f7f22c473cb17df670d6dcd1e1?pvs=4

✨ [Feat] 소셜로그인 - JWT 토큰을 통한 해당 User 정보 조회 기능 구현

---

scapture/src/main/java/com/server/scapture/store/repository/StoreRepository.java
scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
scapture/src/main/java/com/server/scapture/video/dto/GetStoredVideoResponseDto.java
scapture/src/main/java/com/server/scapture/video/service/VideoService.java
scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java

✨ [Feat] 저장 영상 조회 API 구현

---

scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
scapture/src/main/java/com/server/scapture/video/dto/GetVideoDetailResponseDto.java
scapture/src/main/java/com/server/scapture/video/service/VideoService.java
scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java

✨ [Feat] 영상 세부 조회 API 구현 

---

scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
scapture/src/main/java/com/server/scapture/video/service/VideoService.java
scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java

- close #78 
영상 다운로드 권한 조회 API 구현

✨ [Feat] 영상 다운로드 권한 조회 API 구현

---

scapture/src/main/java/com/server/scapture/reservation/controller/ReservationController.java
scapture/src/main/java/com/server/scapture/reservation/repository/ReservationRepository.java
scapture/src/main/java/com/server/scapture/reservation/service/ReservationService.java
scapture/src/main/java/com/server/scapture/reservation/service/ReservationServideImpl.java

✨ [Feat] 구장 예약 API 구현

---

scapture/src/main/java/com/server/scapture/comment/controller/CommentController.java
scapture/src/main/java/com/server/scapture/comment/dto/CreateCommentRequestDto.java
scapture/src/main/java/com/server/scapture/comment/repository/CommentRepository.java
scapture/src/main/java/com/server/scapture/comment/service/CommentService.java
scapture/src/main/java/com/server/scapture/comment/service/CommentServiceImpl.java

✨ [Feat] 댓글 작성 API 구현

---

scapture/src/main/java/com/server/scapture/comment/controller/CommentController.java
scapture/src/main/java/com/server/scapture/comment/service/CommentService.java
scapture/src/main/java/com/server/scapture/comment/service/CommentServiceImpl.java
scapture/src/main/java/com/server/scapture/commentLike/repository/CommentLikeRepository.java
scapture/src/main/java/com/server/scapture/reservation/service/ReservationServiceImpl.java

✨ [Feat] 댓글 좋아요 추가 API 구현

---

scapture/src/main/java/com/server/scapture/comment/controller/CommentController.java
scapture/src/main/java/com/server/scapture/comment/service/CommentService.java
scapture/src/main/java/com/server/scapture/comment/service/CommentServiceImpl.java
scapture/src/main/java/com/server/scapture/domain/Comment.java

✨ [Feat] 댓글 좋아요 해제 API 구현

---

scapture/src/main/java/com/server/scapture/user/controller/UserController.java
scapture/src/main/java/com/server/scapture/user/dto/UserProfileDto.java
scapture/src/main/java/com/server/scapture/user/service/UserService.java
scapture/src/main/java/com/server/scapture/user/service/UserServiceImpl.java

- close #116 
ex) Issue 내용 간단히 기재
- 토큰으로 회원 조회 실패 (404)
- 조회 성공 (200) : 구독중이 아닌 경우
- 조회 성공 (200) : 구독중인 경우
구독 생성 API 구현 후 테스트 예정

✨ [Feat] 프로필 조회 API 구현

---

scapture/src/main/java/com/server/scapture/subscribe/repository/SubscribeRepository.java
scapture/src/main/java/com/server/scapture/subscribe/service/SubscribeService.java
scapture/src/main/java/com/server/scapture/subscribe/service/SubscribeServiceImpl.java

- close #124
ex) Issue 내용 간단히 기재
- checkRole() 생성
- 코드

✨ [Feat] checkTier 메서드 생성

---

scapture/src/main/java/com/server/scapture/user/service/UserServiceImpl.java

- close #124 
프로필 조회 시 Role 정보 업데이트 로직 추가

✨ [Feat] 프로필 조회 API - checkRole() 추가

---

scapture/src/main/java/com/server/scapture/comment/controller/CommentController.java
scapture/src/main/java/com/server/scapture/comment/dto/GetCommentResponseDto.java
scapture/src/main/java/com/server/scapture/comment/repository/CommentRepository.java
scapture/src/main/java/com/server/scapture/comment/service/CommentService.java
scapture/src/main/java/com/server/scapture/comment/service/CommentServiceImpl.java
scapture/src/main/java/com/server/scapture/user/repository/UserRepository.java

✨ [Feat] 댓글 전체 조회 API 구현

---

scapture/src/main/java/com/server/scapture/stadium/service/StadiumServiceImpl.java
scapture/src/main/java/com/server/scapture/util/S3/S3Service.java
scapture/src/main/resources/application.properties

- close #131 
S3 User Profile image 수정 Method 추가

✨ [Feat] S3 User Profile image 수정 Method 추가

---

scapture/src/main/java/com/server/scapture/reservation/repository/ReservationRepository.java
scapture/src/main/java/com/server/scapture/user/controller/UserController.java
scapture/src/main/java/com/server/scapture/user/dto/ReservationResponseDto.java
scapture/src/main/java/com/server/scapture/user/service/UserService.java
scapture/src/main/java/com/server/scapture/user/service/UserServiceImpl.java
scapture/src/main/java/com/server/scapture/util/date/DateUtil.java

- close #118 
회원의 예약 내역 조회 API 구현
1. 조회 성공 - 예약 내역 있는 경우 (200)
- 포스트맨
- DB (userID = 20인 경우 테스트)
<br><br>
2. 조회 성공 - 예약 내역 없는 경우 (200)
- 포스트맨
- DB (userID = 20인 경우 테스트)
<br><br>
3. 회원정보 찾을 수 없는 경우 (404)
- 포스트맨

✨ [Feat] 예약 내역 조회 API 구현

---

scapture/src/main/java/com/server/scapture/util/date/DateUtil.java

- close #134 
- util 패키지 > date 패키지 > DateUtil클래스 안에 formatting 관련 메서드 구현해둠

✨ [Feat] localDateTime formatting 관련 메서드 구현

---

scapture/src/main/java/com/server/scapture/domain/Video.java
scapture/src/main/java/com/server/scapture/video/dto/GetStadiumInfoDto.java
scapture/src/main/java/com/server/scapture/video/dto/GetVideoDetailResponseDto.java
scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java

🚨 [FIx] 영상 세부 조회 API 수정

---

scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java

- close #102 
구장 생성 - 조회 수 생성 추가

🚨 [Fix] 영상 생성 - 조회수 추가 

---

scapture/src/main/java/com/server/scapture/video/dto/GetVideosResponseDto.java
scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java

- close #
경기 영상 조회 API - 조회수 추가

🚨 [Fix] 경기 영상 조회 API - 조회수 추가

---

scapture/src/main/java/com/server/scapture/video/dto/GetVideosByLikeCountResponseDto.java
scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java

🚨 [Fix] 인기 영상 조회 API 수정

---

scapture/src/main/java/com/server/scapture/domain/User.java
scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java

- close #106 
영상 다운로드 권한 부여 API 수정 - 버내너 차감

[Fix] 영상 다운로드 권한 부여 API 수정

---

scapture/src/main/java/com/server/scapture/comment/controller/CommentController.java
scapture/src/main/java/com/server/scapture/comment/service/CommentServiceImpl.java

- close #147 
Comment 조회 API - 로그인 X 사용자 조회 가능 변경

🚨 [Fix] Comment 조회 API

---

scapture/src/main/java/com/server/scapture/schedule/controller/ScheduleController.java
scapture/src/main/java/com/server/scapture/schedule/dto/CreateScheduleRequestDto.java
scapture/src/main/java/com/server/scapture/schedule/service/ScheduleService.java
scapture/src/main/java/com/server/scapture/schedule/service/ScheduleServiceImpl.java

🚨 [Fix] 운영 일정 생성 API 수정

---

scapture/src/main/java/com/server/scapture/comment/dto/GetCommentResponseDto.java
scapture/src/main/java/com/server/scapture/comment/service/CommentServiceImpl.java

- close #154 
Comment Id 함께 전송

🚨 [FIx] 댓글 전체 조회 API 수정

---

scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java

- close #155 
인기 영상 이름 변경(인기 동영상01 ~ 인기동영상10으로 고정)

🚨 [Fix] 인기영상 조회 API 수정

---

scapture/src/main/java/com/server/scapture/user/dto/SubscribeResponseDto.java

- close #158 
소셜로그인 redirect URL 등의 설정을 local -> deploy로 변경

✨ [Release] 소셜로그인 로컬 -> 배포

---

scapture/src/main/java/com/server/scapture/video/dto/GetVideoDetailResponseDto.java
scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java

- close #161 
영상 세부 조회 API 수정 - Response 수정

🚨 [Fix] 영상 세부 조회 API 수정 - Response 수정

---

scapture/src/main/java/com/server/scapture/video/dto/GetStadiumInfoDto.java
scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java

- close #163 
영상 세부 조회 API 수정 - 구장 사진 첨부

🚨 [Fix] 영상 세부 조회 API 수정 - 구장 사진 첨부

---

scapture/src/main/java/com/server/scapture/oauth/dto/SocialLoginResponseDto.java
scapture/src/main/java/com/server/scapture/oauth/service/AbstractSocialLoginService.java

- close #167 
소셜로그인의 응답 형식 변환
data -> data.token

🚨 [Fix] 소셜로그인 - 응답 형식 변환 data -> data.token

---

scapture/src/main/java/com/server/scapture/user/controller/UserController.java

- close #123 
구독중인 경우 프로필 조회 api 테스트
- 포스트맨
- db

✅ [Test] 프로필 조회 - 구독중인 경우 test

---

scapture/src/main/java/com/server/scapture/stadium/dto/GetStadiumDetailDto.java
scapture/src/main/java/com/server/scapture/stadium/service/StadiumServiceImpl.java

- close #171 
Response 운영 시간 추가

🚨 [Fix] 경기장 세부 조회 API - Response 운영 시간 추가

---

scapture/src/main/java/com/server/scapture/reservation/controller/ReservationController.java
scapture/src/main/java/com/server/scapture/reservation/service/ReservationService.java
scapture/src/main/java/com/server/scapture/reservation/service/ReservationServiceImpl.java

- close #173 
구장 예약 일정 조회 API 수정

🚨 [FIx] 구장 예약 일정 조회 API 수정

---

scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java

- close #175 
영상 다운로드 권한 부여 시 사용자 버내너 개수 확인

🚨 [Fix] 영상 다운로드 권한 부여 API 수정

---

scapture/src/main/java/com/server/scapture/stadium/controller/StadiumController.java
scapture/src/main/java/com/server/scapture/stadium/dto/GetMainInfoPopularDto.java
scapture/src/main/java/com/server/scapture/stadium/dto/GetMainInfoResponseDto.java
scapture/src/main/java/com/server/scapture/stadium/dto/GetMainInfoStadiumDto.java
scapture/src/main/java/com/server/scapture/stadium/service/StadiumService.java
scapture/src/main/java/com/server/scapture/stadium/service/StadiumServiceImpl.java
scapture/src/main/java/com/server/scapture/video/repository/VideoRepository.java

✨ [Feat] 메인 페이지 API 구현

---

scapture/src/main/java/com/server/scapture/user/service/UserServiceImpl.java

- close #137 
버내너 잔액조회 하기 전 구독 정보 갱신 메서드 호출

♻️ [Refactoring] 버내너 잔액조회에 checkRoll 추가

---

scapture/src/main/java/com/server/scapture/Ip/repository/IpRepository.java
scapture/src/main/java/com/server/scapture/domain/Ip.java
scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
scapture/src/main/java/com/server/scapture/video/dto/GetRecordInfoResponseDto.java
scapture/src/main/java/com/server/scapture/video/service/VideoService.java
scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java

- close #184 
영상 녹화 정보 조회 API 구현

✨ [Feat] 영상 녹화 정보 조회 API 구현

---

scapture/src/main/java/com/server/scapture/Ip/controller/IpController.java
scapture/src/main/java/com/server/scapture/Ip/dto/CreateIpRequestDto.java
scapture/src/main/java/com/server/scapture/Ip/service/IpService.java
scapture/src/main/java/com/server/scapture/Ip/service/IpServiceImpl.java
scapture/src/main/java/com/server/scapture/video/controller/VideoController.java

✨ [Feat] IP 생성 API 구현

---

scapture/src/main/java/com/server/scapture/schedule/dto/CreateScheduleResponseDto.java
scapture/src/main/java/com/server/scapture/schedule/service/ScheduleServiceImpl.java

- close #188 
운영 시간 생성 API 수정 - Schedule ID Return

🚨 [Fix] 운영 시간 생성 API 수정
